name: scan-image
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
env:
  ORG: "krol"
jobs:

  scan-image:
    name: scanning-image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/${{ env.ORG }}/my-app:${{ github.sha }} .

      - name: Trivy - vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/${{ env.ORG }}/my-app:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'

      - name: Trivy - vulnerability Scanner - sarif.tpl
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/${{ env.ORG }}/my-app:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy.sarif'
          severity: 'HIGH,CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: 'trivy.sarif'
