name: scan-image
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
env:
  ORG: "krol"
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  scan-image:
    name: scan-image
    runs-on: ubuntu-20.04
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/${{ env.ORG }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Trivy - vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/${{ env.ORG }}/${{ env.IMAGE_NAME }}:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'

      - name: Trivy - vulnerability Scanner - sarif
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/${{ env.ORG }}/${{ env.IMAGE_NAME }}:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy.sarif'
          severity: 'HIGH,CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: 'trivy.sarif'
